/*
	LRG MISSION TEMPLATE
	AISpawns.sqf
	Author: MitchJC
	
	Generated by the AISpawns.sqf generator on 2018-10-29, 09:18:40am
*/

//================================= Spawn 1 ==================================

[
    "Bolabongo",
    "Bolabongo",
    550,
    "SLA",
    [0, 50, 300],
    [4, 5],
    [0, 0],
    [2, 3],
    [0, 0],
    [0, 0],
    [0, 0],
    [3, 6],
    [1, 2]
] call LR_fnc_SpawnAI;

