[west, -1, [
  ["Land_vn_bagfence_short_f", 1],
  ["Land_vn_b_trench_revetment_tall_03", 1],
  ["Land_vn_b_trench_revetment_05_01", 1],
  ["Land_vn_b_trench_revetment_tall_09", 1],
  ["Land_Plank_01_8m_F", 1],
  ["Land_Plank_01_4m_F", 1],
  ["Land_vn_b_tower_01", 1],
  ["Land_vn_czechhedgehog_01_f", 1],
  ["Land_Razorwire_F", 1],
  ["Land_vn_b_foxhole_01", 1],
  ["Land_vn_b_trench_stair_01", 1],
  ["Land_vn_b_trench_firing_05", 1],
  ["Land_vn_b_trench_firing_03", 1],
  ["Land_vn_b_trench_bunker_05_01", 1],
  ["Land_vn_b_trench_05_02", 1],
  ["Land_HelipadCircle_F", 1],
  ["Land_PortableLight_single_F", 1],
  ["Land_vn_tent_mash_01_03", 1],
  ["Land_vn_b_trench_bunker_06_01", 1],
  ["Land_vn_b_trench_firing_01", 1]
]] call acex_fortify_fnc_registerObjects;