_crate = _this select 0;
["AmmoboxInit",[_crate,false,{true}]] spawn BIS_fnc_arsenal;

_availableItems = [
"ItemWatch",
"ItemCompass",
"ItemMap",
"LIB_Binocular_GER",
"ACE_CableTie",
"ACE_DefusalKit",
"ACE_EarPlugs",
"ACE_Clacker",
"ACE_DeadManSwitch",
"ACE_Flashlight_XL50",
"ACE_MapTools",
"ACE_wirecutter",
"ACE_RangeTable_82mm",
"ACE_RangeCard",
"ACE_SpraypaintBlack",
"ACE_SpraypaintBlue",
"ACE_SpraypaintGreen",
"ACE_SpraypaintRed",
"ACE_EntrenchingTool",
"ACE_SpareBarrel",
"ACE_atropine",
"ACE_fieldDressing",
"ACE_elasticBandage",
"ACE_quikclot",
"ACE_bloodIV",
"ACE_bloodIV_500",
"ACE_bloodIV_250",
"ACE_bodyBag ",
"ACE_epinephrine",
"ACE_morphine",
"ACE_packingBandage",
"ACE_personalAidKit",
"ACE_plasmaIV",
"ACE_plasmaIV_500",
"ACE_plasmaIV_250",
"ACE_salineIV",
"ACE_salineIV_500",
"ACE_salineIV_250",
"ACE_surgicalKit",
"ACE_tourniquet",
"ACE_Flashlight_MX991",
"ACE_Flashlight",
"ACE_Flashlight_XL50",
"LIB_ToolKit"
];

_availableHeadgear = [
"H_LIB_WP_Helmet",
"H_LIB_WP_Helmet_camo",
"H_LIB_WP_Helmet_med",
"H_LIB_GER_Helmet",
"H_LIB_GER_HelmetCamo",
"H_LIB_GER_Helmet_net_painted",
"H_LIB_GER_Helmet_ns_painted",
"H_LIB_GER_Helmet_painted",
"H_LIB_GER_HelmetCamo2",
"H_LIB_GER_Helmet_net",
"H_LIB_GER_Helmet_ns",
"H_LIB_GER_Cap",
"H_LIB_GER_TankPrivateCap",
"H_LIB_GER_TankOfficerCap",
"H_LIB_GER_TankOfficerCap2",
"H_LIB_GER_OfficerCap",
"H_LIB_GER_SPGPrivateCap",
"H_LIB_GER_LW_PilotHelmet",
"H_LIB_WP_Cap"
];

_availableGoggles = [
"G_LIB_Binoculars",
"G_LIB_Dienst_Brille2",
"G_LIB_Dienst_Brille",
"G_LIB_Dust_Goggles",
"G_LIB_GER_Gloves4",
"G_LIB_GER_Gloves2",
"G_LIB_GER_Gloves1",
"G_LIB_GER_Gloves3",
"G_LIB_Headwrap",
"G_LIB_Headwrap_gloves",
"G_LIB_Scarf2_B",
"G_LIB_Scarf2_G",
"G_LIB_Scarf_B",
"G_LIB_Scarf_G",
"G_LIB_Watch2",
"G_LIB_Watch1"
];
_availableUniforms = [
"U_LIB_GER_Soldier3_w",
"U_LIB_GER_Soldier_camo_w",
"U_LIB_GER_Scharfschutze_w",
"U_LIB_GER_Scharfschutze_2_w",
"U_LIB_GER_LW_pilot",
"U_LIB_GER_Officer_camo",
"U_LIB_GER_Hauptmann",
"U_LIB_GER_Leutnant",
"U_LIB_GER_Oberleutnant",
"U_LIB_GER_Oberst",
"U_LIB_GER_Art_leutnant",
"U_LIB_GER_Gefreiter",
"U_LIB_GER_Oberschutze",
"U_LIB_GER_Recruit",
"U_LIB_GER_Schutze",
"U_LIB_GER_Unterofficer",
"U_LIB_GER_Soldier3",
"U_LIB_GER_Soldier2",
"U_LIB_GER_Art_schutze",
"U_LIB_GER_Art_unterofficer",
"U_LIB_GER_Soldier_camo2",
"U_LIB_GER_Scharfschutze",
"U_LIB_GER_Soldier_camo",
"U_LIB_GER_Soldier_camo4",
"U_LIB_GER_Soldier_camo3",
"U_LIB_GER_Soldier_camo5",
"U_LIB_GER_MG_schutze",
"U_LIB_GER_Medic",
"U_LIB_GER_Spg_crew_leutnant",
"U_LIB_GER_Spg_crew_private",
"U_LIB_GER_Spg_crew_unterofficer"
];

_availableVests = [
"V_LIB_GER_OfficerVest",
"V_LIB_GER_VestG43",
"V_LIB_GER_VestKar98",
"V_LIB_GER_VestMG",
"V_LIB_GER_VestMP40",
"V_LIB_GER_FieldOfficer",
"V_LIB_GER_PioneerVest",
"V_LIB_GER_SniperBelt",
"V_LIB_GER_VestSTG",
"V_LIB_GER_VestUnterofficer",
"V_LIB_GER_OfficerBelt",
"V_LIB_GER_TankPrivateBelt",
"V_LIB_GER_PrivateBelt",
"V_LIB_WP_OfficerVest",
"V_LIB_WP_SniperBela",
"V_LIB_WP_G43Vest",
"V_LIB_WP_Kar98Vest",
"V_LIB_WP_MGVest",
"V_LIB_WP_MP40Vest",
"V_LIB_WP_STGVest"

];

_availableBackpacks = [
"B_LIB_GER_A_frame_kit",
"B_LIB_GER_A_frame_zeltbahn",
"B_LIB_GER_A_frame",
"B_LIB_GER_SapperBackpack_empty",
"B_LIB_GER_Backpack",
"B_LIB_GER_Radio",
"B_LIB_GER_LW_Paradrop",
"B_LIB_GER_Panzer_Empty",
"B_LIB_GER_Tonister34_cowhide",
"B_LIB_GER_MedicBackpack_Empty"
];

_availableAttachments = [
];

_availableMagazines = [
"LIB_10Rnd_792x57",
"LIB_5Rnd_792x57",
"LIB_5Rnd_792x57_t",
"LIB_5Rnd_792x57_sS",
"LIB_5Rnd_792x57_SMK",
"LIB_10Rnd_792x57_T",
"LIB_10Rnd_792x57_T2",
"LIB_10Rnd_792x57_sS",
"LIB_10Rnd_792x57_SMK",
"LIB_50Rnd_792x57",
"LIB_50Rnd_792x57_SMK",
"LIB_50Rnd_792x57_sS",
"LIB_75Rnd_792x57",
"LIB_32Rnd_9x19",
"LIB_30Rnd_792x33",
"LIB_1rnd_81mmHE_GRWR34",
"LIB_81mm_GRWR34_SmokeShell",
"LIB_1Rnd_flare_white",
"LIB_1Rnd_flare_red",
"LIB_1Rnd_flare_green",
"LIB_1Rnd_flare_yellow",
"LIB_1Rnd_PzFaust_30m",
"LIB_1Rnd_RPzB",
"LIB_8Rnd_9x19",
"LIB_8Rnd_9x19_P08",
"LIB_100Rnd_792x57",
"LIB_shg24",
"LIB_shg24x7",
"LIB_m39",
"LIB_nb39",
"LIB_pwm",
"LIB_STMI_MINE_mag",
"LIB_SMI_35_1_MINE_mag",
"LIB_SMI_35_MINE_mag",
"LIB_shumine_42_MINE_mag",
"APERSTripMine_Wire_Mag",
"LIB_US_TNT_4pound_mag",
"LIB_Ladung_Big_MINE_mag",
"LIB_Ladung_Small_MINE_mag"
];

_availableWeapons = [
"LIB_GrWr34_Barrel",
"LIB_GrWr34_Tripod",
"LIB_Laffete_Tripod",
"LIB_PzFaust_30m",
"LIB_RPzB",
"LIB_RPzB_w",
"LIB_FLARE_PISTOL",
"LIB_P08",
"LIB_P38",
"LIB_MP44",
"LIB_MP40",
"LIB_MG42",
"LIB_MG34_PT",
"LIB_MG34",
"LIB_K98ZF39",
"LIB_K98",
"LIB_G43",
"LIB_G3340"
];


[_crate,((backpackCargo _crate) + _availableBackpacks)] call BIS_fnc_addVirtualBackpackCargo;
[_crate,((itemCargo _crate) + _availableHeadgear + _availableGoggles + _availableUniforms + _availableVests + _availableAttachments + _availableItems)] call BIS_fnc_addVirtualItemCargo;
[_crate,((magazineCargo _crate) + _availableMagazines )] call BIS_fnc_addVirtualMagazineCargo;
[_crate,((weaponCargo _crate) +_availableWeapons)] call BIS_fnc_addVirtualWeaponCargo;